name: "Release Management Action"
description: "Github action for managing the release version and tags based on the release type."
inputs:
  token:
    description: "The token to use to access the GitHub API"
    required: true
  "config-path":
    description: "Configuration file path to use for identifying sub project paths, Ex - .github/config/release-management.yaml"
    required: true
  "commit-limit":
    description: "Number of commits use for analyzing to generate next release version, default limit is 250"
    required: false
  timezone:
    description: "Timezone to use for generating release version, default timezone is Malaysia Time(+08:00). Ex - +04:00 (New york Time)"
    required: false
  "release-prefix":
    description: "Release prefix to use for generating release version, default prefix is v"
    required: false
  "release-suffix":
    description: "Release suffix to use for generating release version, default suffix is empty"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
