name: Release Management

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  init-release:
    if: github.event.pull_request.merged && (startsWith(github.event.pull_request.head.ref, 'flight/') || startsWith(github.event.pull_request.head.ref, 'hotfix/'))
    runs-on: ubuntu-latest
    name: Create Release PR
    steps:
      - name: Release
        uses: respond-io/release-management-action@flight/main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/config/release-management.yaml
          release-prefix: v
          action: release-pr 
  release:
    if: github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    name: Tagging and Releasing
    steps:
      - name: Release
        uses: respond-io/release-management-action@flight/main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/config/release-management.yaml
          release-prefix: v
          action: release
