on:
  push:
    branches:
      - main
name: release-please

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci --ignore-scripts
      - run: npm test
      - run: npm run build

  create_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          extra-files: |
            dist/index.js
